[package]
name = "rust-cross-compiler-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
strip = "debuginfo" ## Makes the binaries much smaller, but removes debuginfo
